### ISSUE TITLE
FTEvent: a new comment number is "prepended" at each edit

### ISSUE THREAD

**Issue by mpacary** [xsericon/vizop-latest#11]
Currently, each time a comment is edited, a number is "prepended" at the beginning of that comment (screenshot below)
Should this behavior be modified so that there is always one (& only one) number before the comment?
Should a "prefix" number be added at all?

![image](https://user-images.githubusercontent.com/705663/99684608-ef5e1400-2a81-11eb-879b-ecbae334f91b.png)

**Comment by pgclarke** [comment]
Fixed by a code edit in PopulateFTEvent(). Similar problem did not exist for FT connectors because the code for unpacking comments in PopulateFTConnector() is different.
