### ISSUE TITLE
SIF properties: black area hiding parts of the informations

### ISSUE THREAD

**Issue by mpacary** [xsericon/vizop-latest#7]
Right after choosing fault tree PHA model, the SIF properties are partially hidden by a black area :

![image](https://user-images.githubusercontent.com/705663/73118785-3ad68d00-3f59-11ea-8ece-9155aa46f53b.png)

**Comment by mpacary** [comment]
Dragging the pane content does not "remove" the black area, however adding an "initiating event" all displayed elements become entierely visible again.

**Comment by pgclarke** [comment]
I guess it is a screen refresh issue. I don't have that exact problem on Mac, though I see different refresh issues. Let's ignore it for now and fix it later if it remains a problem.

**Comment by mpacary** [comment]
Cannot reproduce today ➡️ closing
