### ISSUE TITLE
Depending on screen resolution, parts of UI can be hidden

### ISSUE THREAD

**Issue by mpacary** [xsericon/vizop-latest#8]
On my screen, some buttons are partially hidden ; maybe scrollbars could be added / some panes resized to have a minimum width or height?

![image](https://user-images.githubusercontent.com/705663/73120297-55fec800-3f6c-11ea-87fa-3be08be654d0.png)

**Comment by pgclarke** [comment]
(Peter, 25 Jan) Relocated Cancel and Go buttons to the right of the "Fault tree style" box. Hopefully this will resolve the problem in the Edit panel (big panel at the top).
For the Control panel (smaller panel below the Edit panel), the problem widgets should not be displayed at all. The problem will hopefully disappear when the Control panel widget lineup is completed later.

**Comment by mpacary** [comment]
> Relocated Cancel and Go buttons to the right of the "Fault tree style" box. Hopefully this will resolve the problem in the Edit panel (big panel at the top).
Fixed by @pgclarke 👍 
> For the Control panel (smaller panel below the Edit panel), the problem widgets should not be displayed at all. The problem will hopefully disappear when the Control panel widget lineup is completed later.
If this is WIP, it guess this should not be considered as a bug.

➡️ closing for now, feel free to reopen if necessary.
